name: Deploy to Dataproc

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/150195794927/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-ci@project-34c13448-074a-417a-b64.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Set GCP project
        run: gcloud config set project project-34c13448-074a-417a-b64

      - name: Build fat jar (sbt assembly)
        run: sbt clean assembly

      - name: Upload jar to GCS
        run: |
          JAR_PATH=$(ls target/scala-*/spark-ecommerce-analytics-assembly-*.jar | head -n 1)
          echo "Uploading jar: $JAR_PATH"
          gcloud storage cp "$JAR_PATH" gs://vinay-ecommerce-dataproc-6731/jars/spark-ecommerce-analytics-assembly-1.0.jar

      - name: Upload data to GCS
        run: |
          gcloud storage cp data/*.csv gs://vinay-ecommerce-dataproc-6731/data/

      - name: Submit Spark job to Dataproc
        run: |
          gcloud dataproc jobs submit spark \
            --project=project-34c13448-074a-417a-b64 \
            --region=northamerica-northeast1 \
            --cluster=ecommerce-cluster \
            --class=com.analytics.MainApp \
            --jars=gs://vinay-ecommerce-dataproc-6731/jars/spark-ecommerce-analytics-assembly-1.0.jar \
            --properties=spark.yarn.appMasterEnv.DATA_PATH=gs://vinay-ecommerce-dataproc-6731/data,spark.executorEnv.DATA_PATH=gs://vinay-ecommerce-dataproc-6731/data
