name: Deploy to Dataproc

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/150195794927/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-ci@project-34c13448-074a-417a-b64.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set GCP project
        run: gcloud config set project project-34c13448-074a-417a-b64

      
      - name: Verify auth
        run: gcloud auth list

      - name: Upload data to GCS
        run: |
          gcloud storage cp data/*.csv gs://vinay-ecommerce-dataproc-6731/data/

      - name: Submit Spark job to Dataproc
        run: |
          gcloud dataproc jobs submit spark \
            --project=project-34c13448-074a-417a-b64 \
            --region=northamerica-northeast1 \
            --cluster=ecommerce-cluster \
            --class=your.main.Class \
            --jars=gs://vinay-ecommerce-dataproc-6731/jars/spark-ecommerce-analytics-assembly-1.0.jar
